-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity process_features_squash_Pipeline_VITIS_LOOP_294_5 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    output_buffer_3_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    output_buffer_3_ce0 : OUT STD_LOGIC;
    output_buffer_3_we0 : OUT STD_LOGIC;
    output_buffer_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    output_buffer_3_address1 : OUT STD_LOGIC_VECTOR (11 downto 0);
    output_buffer_3_ce1 : OUT STD_LOGIC;
    output_buffer_3_we1 : OUT STD_LOGIC;
    output_buffer_3_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    output_buffer_2_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    output_buffer_2_ce0 : OUT STD_LOGIC;
    output_buffer_2_we0 : OUT STD_LOGIC;
    output_buffer_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    output_buffer_2_address1 : OUT STD_LOGIC_VECTOR (11 downto 0);
    output_buffer_2_ce1 : OUT STD_LOGIC;
    output_buffer_2_we1 : OUT STD_LOGIC;
    output_buffer_2_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    output_buffer_1_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    output_buffer_1_ce0 : OUT STD_LOGIC;
    output_buffer_1_we0 : OUT STD_LOGIC;
    output_buffer_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    output_buffer_1_address1 : OUT STD_LOGIC_VECTOR (11 downto 0);
    output_buffer_1_ce1 : OUT STD_LOGIC;
    output_buffer_1_we1 : OUT STD_LOGIC;
    output_buffer_1_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    output_buffer_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    output_buffer_ce0 : OUT STD_LOGIC;
    output_buffer_we0 : OUT STD_LOGIC;
    output_buffer_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    output_buffer_address1 : OUT STD_LOGIC_VECTOR (11 downto 0);
    output_buffer_ce1 : OUT STD_LOGIC;
    output_buffer_we1 : OUT STD_LOGIC;
    output_buffer_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    scale_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    scale_ce0 : OUT STD_LOGIC;
    scale_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    input_buffer_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    input_buffer_ce0 : OUT STD_LOGIC;
    input_buffer_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    input_buffer_address1 : OUT STD_LOGIC_VECTOR (11 downto 0);
    input_buffer_ce1 : OUT STD_LOGIC;
    input_buffer_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    input_buffer_1_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    input_buffer_1_ce0 : OUT STD_LOGIC;
    input_buffer_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    input_buffer_1_address1 : OUT STD_LOGIC_VECTOR (11 downto 0);
    input_buffer_1_ce1 : OUT STD_LOGIC;
    input_buffer_1_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    input_buffer_2_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    input_buffer_2_ce0 : OUT STD_LOGIC;
    input_buffer_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    input_buffer_2_address1 : OUT STD_LOGIC_VECTOR (11 downto 0);
    input_buffer_2_ce1 : OUT STD_LOGIC;
    input_buffer_2_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    input_buffer_3_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    input_buffer_3_ce0 : OUT STD_LOGIC;
    input_buffer_3_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    input_buffer_3_address1 : OUT STD_LOGIC_VECTOR (11 downto 0);
    input_buffer_3_ce1 : OUT STD_LOGIC;
    input_buffer_3_q1 : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of process_features_squash_Pipeline_VITIS_LOOP_294_5 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv11_480 : STD_LOGIC_VECTOR (10 downto 0) := "10010000000";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln294_fu_329_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal p_cast28_fu_348_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_cast28_reg_686 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_cast28_reg_686_pp0_iter1_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln298_fu_372_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln298_reg_719 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln298_reg_719_pp0_iter1_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln3_reg_747 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln298_1_reg_753 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln298_2_reg_759 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln298_3_reg_765 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln298_4_reg_771 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln298_5_reg_777 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln298_6_reg_783 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln298_7_reg_789 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln294_fu_335_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal grid_rows_fu_56 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    signal add_ln294_fu_323_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_grid_rows_1 : STD_LOGIC_VECTOR (10 downto 0);
    signal scale_ce0_local : STD_LOGIC;
    signal input_buffer_ce1_local : STD_LOGIC;
    signal input_buffer_ce0_local : STD_LOGIC;
    signal input_buffer_1_ce1_local : STD_LOGIC;
    signal input_buffer_1_ce0_local : STD_LOGIC;
    signal input_buffer_2_ce1_local : STD_LOGIC;
    signal input_buffer_2_ce0_local : STD_LOGIC;
    signal input_buffer_3_ce1_local : STD_LOGIC;
    signal input_buffer_3_ce0_local : STD_LOGIC;
    signal output_buffer_we1_local : STD_LOGIC;
    signal output_buffer_ce1_local : STD_LOGIC;
    signal output_buffer_we0_local : STD_LOGIC;
    signal output_buffer_ce0_local : STD_LOGIC;
    signal output_buffer_1_we1_local : STD_LOGIC;
    signal output_buffer_1_ce1_local : STD_LOGIC;
    signal output_buffer_1_we0_local : STD_LOGIC;
    signal output_buffer_1_ce0_local : STD_LOGIC;
    signal output_buffer_2_we1_local : STD_LOGIC;
    signal output_buffer_2_ce1_local : STD_LOGIC;
    signal output_buffer_2_we0_local : STD_LOGIC;
    signal output_buffer_2_ce0_local : STD_LOGIC;
    signal output_buffer_3_we1_local : STD_LOGIC;
    signal output_buffer_3_ce1_local : STD_LOGIC;
    signal output_buffer_3_we0_local : STD_LOGIC;
    signal output_buffer_3_ce0_local : STD_LOGIC;
    signal mul_ln298_fu_273_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln298_fu_420_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal mul_ln298_1_fu_277_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln298_2_fu_281_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln298_3_fu_285_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln298_4_fu_289_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln298_5_fu_293_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln298_6_fu_297_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln298_7_fu_301_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_s_fu_340_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal or_ln2_fu_364_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal mul_ln298_fu_273_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal mul_ln298_1_fu_277_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal mul_ln298_2_fu_281_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal mul_ln298_3_fu_285_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal mul_ln298_4_fu_289_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal mul_ln298_5_fu_293_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal mul_ln298_6_fu_297_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal mul_ln298_7_fu_301_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component process_features_mul_32s_32s_48_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        dout : OUT STD_LOGIC_VECTOR (47 downto 0) );
    end component;


    component process_features_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_32s_32s_48_1_1_U668 : component process_features_mul_32s_32s_48_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 48)
    port map (
        din0 => input_buffer_q1,
        din1 => mul_ln298_fu_273_p1,
        dout => mul_ln298_fu_273_p2);

    mul_32s_32s_48_1_1_U669 : component process_features_mul_32s_32s_48_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 48)
    port map (
        din0 => input_buffer_1_q1,
        din1 => mul_ln298_1_fu_277_p1,
        dout => mul_ln298_1_fu_277_p2);

    mul_32s_32s_48_1_1_U670 : component process_features_mul_32s_32s_48_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 48)
    port map (
        din0 => input_buffer_2_q1,
        din1 => mul_ln298_2_fu_281_p1,
        dout => mul_ln298_2_fu_281_p2);

    mul_32s_32s_48_1_1_U671 : component process_features_mul_32s_32s_48_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 48)
    port map (
        din0 => input_buffer_3_q1,
        din1 => mul_ln298_3_fu_285_p1,
        dout => mul_ln298_3_fu_285_p2);

    mul_32s_32s_48_1_1_U672 : component process_features_mul_32s_32s_48_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 48)
    port map (
        din0 => input_buffer_q0,
        din1 => mul_ln298_4_fu_289_p1,
        dout => mul_ln298_4_fu_289_p2);

    mul_32s_32s_48_1_1_U673 : component process_features_mul_32s_32s_48_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 48)
    port map (
        din0 => input_buffer_1_q0,
        din1 => mul_ln298_5_fu_293_p1,
        dout => mul_ln298_5_fu_293_p2);

    mul_32s_32s_48_1_1_U674 : component process_features_mul_32s_32s_48_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 48)
    port map (
        din0 => input_buffer_2_q0,
        din1 => mul_ln298_6_fu_297_p1,
        dout => mul_ln298_6_fu_297_p2);

    mul_32s_32s_48_1_1_U675 : component process_features_mul_32s_32s_48_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 48)
    port map (
        din0 => input_buffer_3_q0,
        din1 => mul_ln298_7_fu_301_p1,
        dout => mul_ln298_7_fu_301_p2);

    flow_control_loop_pipe_sequential_init_U : component process_features_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    grid_rows_fu_56_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln294_fu_329_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    grid_rows_fu_56 <= add_ln294_fu_323_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    grid_rows_fu_56 <= ap_const_lv11_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                    p_cast28_reg_686(11 downto 1) <= p_cast28_fu_348_p1(11 downto 1);
                    p_cast28_reg_686_pp0_iter1_reg(11 downto 1) <= p_cast28_reg_686(11 downto 1);
                trunc_ln298_1_reg_753 <= mul_ln298_1_fu_277_p2(47 downto 16);
                trunc_ln298_2_reg_759 <= mul_ln298_2_fu_281_p2(47 downto 16);
                trunc_ln298_3_reg_765 <= mul_ln298_3_fu_285_p2(47 downto 16);
                trunc_ln298_4_reg_771 <= mul_ln298_4_fu_289_p2(47 downto 16);
                trunc_ln298_5_reg_777 <= mul_ln298_5_fu_293_p2(47 downto 16);
                trunc_ln298_6_reg_783 <= mul_ln298_6_fu_297_p2(47 downto 16);
                trunc_ln298_7_reg_789 <= mul_ln298_7_fu_301_p2(47 downto 16);
                trunc_ln3_reg_747 <= mul_ln298_fu_273_p2(47 downto 16);
                    zext_ln298_reg_719(11 downto 1) <= zext_ln298_fu_372_p1(11 downto 1);
                    zext_ln298_reg_719_pp0_iter1_reg(11 downto 1) <= zext_ln298_reg_719(11 downto 1);
            end if;
        end if;
    end process;
    p_cast28_reg_686(0) <= '0';
    p_cast28_reg_686(63 downto 12) <= "0000000000000000000000000000000000000000000000000000";
    p_cast28_reg_686_pp0_iter1_reg(0) <= '0';
    p_cast28_reg_686_pp0_iter1_reg(63 downto 12) <= "0000000000000000000000000000000000000000000000000000";
    zext_ln298_reg_719(0) <= '1';
    zext_ln298_reg_719(63 downto 12) <= "0000000000000000000000000000000000000000000000000000";
    zext_ln298_reg_719_pp0_iter1_reg(0) <= '1';
    zext_ln298_reg_719_pp0_iter1_reg(63 downto 12) <= "0000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln294_fu_323_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_grid_rows_1) + unsigned(ap_const_lv11_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln294_fu_329_p2)
    begin
        if (((icmp_ln294_fu_329_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_grid_rows_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, grid_rows_fu_56, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_grid_rows_1 <= ap_const_lv11_0;
        else 
            ap_sig_allocacmp_grid_rows_1 <= grid_rows_fu_56;
        end if; 
    end process;

    icmp_ln294_fu_329_p2 <= "1" when (ap_sig_allocacmp_grid_rows_1 = ap_const_lv11_480) else "0";
    input_buffer_1_address0 <= zext_ln298_fu_372_p1(12 - 1 downto 0);
    input_buffer_1_address1 <= p_cast28_fu_348_p1(12 - 1 downto 0);
    input_buffer_1_ce0 <= input_buffer_1_ce0_local;

    input_buffer_1_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            input_buffer_1_ce0_local <= ap_const_logic_1;
        else 
            input_buffer_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    input_buffer_1_ce1 <= input_buffer_1_ce1_local;

    input_buffer_1_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            input_buffer_1_ce1_local <= ap_const_logic_1;
        else 
            input_buffer_1_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    input_buffer_2_address0 <= zext_ln298_fu_372_p1(12 - 1 downto 0);
    input_buffer_2_address1 <= p_cast28_fu_348_p1(12 - 1 downto 0);
    input_buffer_2_ce0 <= input_buffer_2_ce0_local;

    input_buffer_2_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            input_buffer_2_ce0_local <= ap_const_logic_1;
        else 
            input_buffer_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    input_buffer_2_ce1 <= input_buffer_2_ce1_local;

    input_buffer_2_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            input_buffer_2_ce1_local <= ap_const_logic_1;
        else 
            input_buffer_2_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    input_buffer_3_address0 <= zext_ln298_fu_372_p1(12 - 1 downto 0);
    input_buffer_3_address1 <= p_cast28_fu_348_p1(12 - 1 downto 0);
    input_buffer_3_ce0 <= input_buffer_3_ce0_local;

    input_buffer_3_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            input_buffer_3_ce0_local <= ap_const_logic_1;
        else 
            input_buffer_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    input_buffer_3_ce1 <= input_buffer_3_ce1_local;

    input_buffer_3_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            input_buffer_3_ce1_local <= ap_const_logic_1;
        else 
            input_buffer_3_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    input_buffer_address0 <= zext_ln298_fu_372_p1(12 - 1 downto 0);
    input_buffer_address1 <= p_cast28_fu_348_p1(12 - 1 downto 0);
    input_buffer_ce0 <= input_buffer_ce0_local;

    input_buffer_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            input_buffer_ce0_local <= ap_const_logic_1;
        else 
            input_buffer_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    input_buffer_ce1 <= input_buffer_ce1_local;

    input_buffer_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            input_buffer_ce1_local <= ap_const_logic_1;
        else 
            input_buffer_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    mul_ln298_1_fu_277_p1 <= sext_ln298_fu_420_p1(32 - 1 downto 0);
    mul_ln298_2_fu_281_p1 <= sext_ln298_fu_420_p1(32 - 1 downto 0);
    mul_ln298_3_fu_285_p1 <= sext_ln298_fu_420_p1(32 - 1 downto 0);
    mul_ln298_4_fu_289_p1 <= sext_ln298_fu_420_p1(32 - 1 downto 0);
    mul_ln298_5_fu_293_p1 <= sext_ln298_fu_420_p1(32 - 1 downto 0);
    mul_ln298_6_fu_297_p1 <= sext_ln298_fu_420_p1(32 - 1 downto 0);
    mul_ln298_7_fu_301_p1 <= sext_ln298_fu_420_p1(32 - 1 downto 0);
    mul_ln298_fu_273_p1 <= sext_ln298_fu_420_p1(32 - 1 downto 0);
    or_ln2_fu_364_p3 <= (ap_sig_allocacmp_grid_rows_1 & ap_const_lv1_1);
    output_buffer_1_address0 <= zext_ln298_reg_719_pp0_iter1_reg(12 - 1 downto 0);
    output_buffer_1_address1 <= p_cast28_reg_686_pp0_iter1_reg(12 - 1 downto 0);
    output_buffer_1_ce0 <= output_buffer_1_ce0_local;

    output_buffer_1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            output_buffer_1_ce0_local <= ap_const_logic_1;
        else 
            output_buffer_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    output_buffer_1_ce1 <= output_buffer_1_ce1_local;

    output_buffer_1_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            output_buffer_1_ce1_local <= ap_const_logic_1;
        else 
            output_buffer_1_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    output_buffer_1_d0 <= trunc_ln298_5_reg_777;
    output_buffer_1_d1 <= trunc_ln298_1_reg_753;
    output_buffer_1_we0 <= output_buffer_1_we0_local;

    output_buffer_1_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            output_buffer_1_we0_local <= ap_const_logic_1;
        else 
            output_buffer_1_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    output_buffer_1_we1 <= output_buffer_1_we1_local;

    output_buffer_1_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            output_buffer_1_we1_local <= ap_const_logic_1;
        else 
            output_buffer_1_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    output_buffer_2_address0 <= zext_ln298_reg_719_pp0_iter1_reg(12 - 1 downto 0);
    output_buffer_2_address1 <= p_cast28_reg_686_pp0_iter1_reg(12 - 1 downto 0);
    output_buffer_2_ce0 <= output_buffer_2_ce0_local;

    output_buffer_2_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            output_buffer_2_ce0_local <= ap_const_logic_1;
        else 
            output_buffer_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    output_buffer_2_ce1 <= output_buffer_2_ce1_local;

    output_buffer_2_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            output_buffer_2_ce1_local <= ap_const_logic_1;
        else 
            output_buffer_2_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    output_buffer_2_d0 <= trunc_ln298_6_reg_783;
    output_buffer_2_d1 <= trunc_ln298_2_reg_759;
    output_buffer_2_we0 <= output_buffer_2_we0_local;

    output_buffer_2_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            output_buffer_2_we0_local <= ap_const_logic_1;
        else 
            output_buffer_2_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    output_buffer_2_we1 <= output_buffer_2_we1_local;

    output_buffer_2_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            output_buffer_2_we1_local <= ap_const_logic_1;
        else 
            output_buffer_2_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    output_buffer_3_address0 <= zext_ln298_reg_719_pp0_iter1_reg(12 - 1 downto 0);
    output_buffer_3_address1 <= p_cast28_reg_686_pp0_iter1_reg(12 - 1 downto 0);
    output_buffer_3_ce0 <= output_buffer_3_ce0_local;

    output_buffer_3_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            output_buffer_3_ce0_local <= ap_const_logic_1;
        else 
            output_buffer_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    output_buffer_3_ce1 <= output_buffer_3_ce1_local;

    output_buffer_3_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            output_buffer_3_ce1_local <= ap_const_logic_1;
        else 
            output_buffer_3_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    output_buffer_3_d0 <= trunc_ln298_7_reg_789;
    output_buffer_3_d1 <= trunc_ln298_3_reg_765;
    output_buffer_3_we0 <= output_buffer_3_we0_local;

    output_buffer_3_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            output_buffer_3_we0_local <= ap_const_logic_1;
        else 
            output_buffer_3_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    output_buffer_3_we1 <= output_buffer_3_we1_local;

    output_buffer_3_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            output_buffer_3_we1_local <= ap_const_logic_1;
        else 
            output_buffer_3_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    output_buffer_address0 <= zext_ln298_reg_719_pp0_iter1_reg(12 - 1 downto 0);
    output_buffer_address1 <= p_cast28_reg_686_pp0_iter1_reg(12 - 1 downto 0);
    output_buffer_ce0 <= output_buffer_ce0_local;

    output_buffer_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            output_buffer_ce0_local <= ap_const_logic_1;
        else 
            output_buffer_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    output_buffer_ce1 <= output_buffer_ce1_local;

    output_buffer_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            output_buffer_ce1_local <= ap_const_logic_1;
        else 
            output_buffer_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    output_buffer_d0 <= trunc_ln298_4_reg_771;
    output_buffer_d1 <= trunc_ln3_reg_747;
    output_buffer_we0 <= output_buffer_we0_local;

    output_buffer_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            output_buffer_we0_local <= ap_const_logic_1;
        else 
            output_buffer_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    output_buffer_we1 <= output_buffer_we1_local;

    output_buffer_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            output_buffer_we1_local <= ap_const_logic_1;
        else 
            output_buffer_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_cast28_fu_348_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_340_p3),64));
    scale_address0 <= zext_ln294_fu_335_p1(11 - 1 downto 0);
    scale_ce0 <= scale_ce0_local;

    scale_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            scale_ce0_local <= ap_const_logic_1;
        else 
            scale_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

        sext_ln298_fu_420_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(scale_q0),48));

    tmp_s_fu_340_p3 <= (ap_sig_allocacmp_grid_rows_1 & ap_const_lv1_0);
    zext_ln294_fu_335_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_grid_rows_1),64));
    zext_ln298_fu_372_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln2_fu_364_p3),64));
end behav;
