// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module process_features_squash_Pipeline_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_buffer_3_address0,
        input_buffer_3_ce0,
        input_buffer_3_we0,
        input_buffer_3_d0,
        input_buffer_2_address0,
        input_buffer_2_ce0,
        input_buffer_2_we0,
        input_buffer_2_d0,
        input_buffer_1_address0,
        input_buffer_1_ce0,
        input_buffer_1_we0,
        input_buffer_1_d0,
        input_buffer_address0,
        input_buffer_ce0,
        input_buffer_we0,
        input_buffer_d0,
        input_r_address0,
        input_r_ce0,
        input_r_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [11:0] input_buffer_3_address0;
output   input_buffer_3_ce0;
output   input_buffer_3_we0;
output  [31:0] input_buffer_3_d0;
output  [11:0] input_buffer_2_address0;
output   input_buffer_2_ce0;
output   input_buffer_2_we0;
output  [31:0] input_buffer_2_d0;
output  [11:0] input_buffer_1_address0;
output   input_buffer_1_ce0;
output   input_buffer_1_we0;
output  [31:0] input_buffer_1_d0;
output  [11:0] input_buffer_address0;
output   input_buffer_ce0;
output   input_buffer_we0;
output  [31:0] input_buffer_d0;
output  [13:0] input_r_address0;
output   input_r_ce0;
input  [31:0] input_r_q0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] exitcond296_fu_153_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [1:0] empty_64_fu_164_p1;
reg   [1:0] empty_64_reg_230;
wire    ap_block_pp0_stage0_11001;
reg   [11:0] tmp_13_reg_234;
wire   [63:0] loop_index214_cast22_fu_159_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] p_cast_fu_194_p1;
reg   [13:0] loop_index214_fu_52;
wire   [13:0] empty_fu_147_p2;
wire    ap_loop_init;
reg   [13:0] ap_sig_allocacmp_loop_index214_load;
reg    input_r_ce0_local;
reg    input_buffer_2_we0_local;
reg    input_buffer_2_ce0_local;
reg    input_buffer_1_we0_local;
reg    input_buffer_1_ce0_local;
reg    input_buffer_we0_local;
reg    input_buffer_ce0_local;
reg    input_buffer_3_we0_local;
reg    input_buffer_3_ce0_local;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 loop_index214_fu_52 = 14'd0;
#0 ap_done_reg = 1'b0;
end

process_features_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((exitcond296_fu_153_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            loop_index214_fu_52 <= empty_fu_147_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            loop_index214_fu_52 <= 14'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_64_reg_230 <= empty_64_fu_164_p1;
        tmp_13_reg_234 <= {{ap_sig_allocacmp_loop_index214_load[13:2]}};
    end
end

always @ (*) begin
    if (((exitcond296_fu_153_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_loop_index214_load = 14'd0;
    end else begin
        ap_sig_allocacmp_loop_index214_load = loop_index214_fu_52;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_buffer_1_ce0_local = 1'b1;
    end else begin
        input_buffer_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((empty_64_reg_230 == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_buffer_1_we0_local = 1'b1;
    end else begin
        input_buffer_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_buffer_2_ce0_local = 1'b1;
    end else begin
        input_buffer_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((empty_64_reg_230 == 2'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_buffer_2_we0_local = 1'b1;
    end else begin
        input_buffer_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_buffer_3_ce0_local = 1'b1;
    end else begin
        input_buffer_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((empty_64_reg_230 == 2'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_buffer_3_we0_local = 1'b1;
    end else begin
        input_buffer_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_buffer_ce0_local = 1'b1;
    end else begin
        input_buffer_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((empty_64_reg_230 == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_buffer_we0_local = 1'b1;
    end else begin
        input_buffer_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_r_ce0_local = 1'b1;
    end else begin
        input_r_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign empty_64_fu_164_p1 = ap_sig_allocacmp_loop_index214_load[1:0];

assign empty_fu_147_p2 = (ap_sig_allocacmp_loop_index214_load + 14'd1);

assign exitcond296_fu_153_p2 = ((ap_sig_allocacmp_loop_index214_load == 14'd9216) ? 1'b1 : 1'b0);

assign input_buffer_1_address0 = p_cast_fu_194_p1;

assign input_buffer_1_ce0 = input_buffer_1_ce0_local;

assign input_buffer_1_d0 = input_r_q0;

assign input_buffer_1_we0 = input_buffer_1_we0_local;

assign input_buffer_2_address0 = p_cast_fu_194_p1;

assign input_buffer_2_ce0 = input_buffer_2_ce0_local;

assign input_buffer_2_d0 = input_r_q0;

assign input_buffer_2_we0 = input_buffer_2_we0_local;

assign input_buffer_3_address0 = p_cast_fu_194_p1;

assign input_buffer_3_ce0 = input_buffer_3_ce0_local;

assign input_buffer_3_d0 = input_r_q0;

assign input_buffer_3_we0 = input_buffer_3_we0_local;

assign input_buffer_address0 = p_cast_fu_194_p1;

assign input_buffer_ce0 = input_buffer_ce0_local;

assign input_buffer_d0 = input_r_q0;

assign input_buffer_we0 = input_buffer_we0_local;

assign input_r_address0 = loop_index214_cast22_fu_159_p1;

assign input_r_ce0 = input_r_ce0_local;

assign loop_index214_cast22_fu_159_p1 = ap_sig_allocacmp_loop_index214_load;

assign p_cast_fu_194_p1 = tmp_13_reg_234;

endmodule //process_features_squash_Pipeline_2
